{% set name = "fpsim2" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chembl/FPSim2/archive/{{ version }}.tar.gz
  sha256: 36aa0a700ca4dfb00b025be4533f6576211516c956fe37a5cabf60e706ce568a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.14
    - pybind11 >=2.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytables >=3.4.4
    - rdkit >=2018.09
    - scipy
    - tqdm

test:
  imports:
    - FPSim2
  source_files:
    - tests/**
    - pytest.ini
  requires:
    - pytest
  commands:
    - pytest --verbose tests/

about:
  home: https://github.com/chembl/FPSim2
  license: MIT
  license_file: LICENSE
  summary: Simple package for fast molecular similarity searches

extra:
  recipe-maintainers:
    - hadim
